### ISSUE TITLE
gasket as a module

### ISSUE THREAD

**Issue by sallespro** [datproject/gasket#20]
hi, i'm having a great time discovering dat tools.
i bumped into this error trying to use gasket as a module's example.
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: This socket is closed.
    at Socket._write (net.js:638:19)
    at doWrite (_stream_writable.js:226:10)
    at writeOrBuffer (_stream_writable.js:216:5)
    at Socket.Writable.write (_stream_writable.js:183:11)
    at Socket.write (net.js:616:40)
    at Duplexify._write (/home/me/node/dat/node_modules/gasket/node_modules/duplexify/index.js:197:22)
    at doWrite (/home/me/node/dat/node_modules/gasket/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:237:10)
    at writeOrBuffer (/home/me/node/dat/node_modules/gasket/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:227:5)
    at Writable.write (/home/me/node/dat/node_modules/gasket/node_modules/duplexify/node_modules/readable-stream/lib/_stream_writable.js:194:11)
    at write (/home/me/node/dat/node_modules/gasket/node_modules/duplexify/node_modules/readable-stream/lib/_stream_readable.js:623:24)

```

**Comment by maxogden** [comment]
ah sorry, we are doing some heavy dev on gasket at the moment. I think if you use 1.4.0 it should work (hopefully). we will update the docs soon

**Comment by sallespro** [comment]
that's good to know. having some resque style job control would be interesting. i am working with a use case of having to process large contact lists and manage intermediate lists.
i am very glad to hack around docker-adventure-time and all that. thank you !
